```python
from aws_cdk import core
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_deployment as s3deploy
from aws_cdk import aws_s3_event_notifications as s3en
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_lambda_python as _lambda_python
from aws_cdk import aws_apigateway as apigw
from aws_cdk import aws_sns as sns
from aws_cdk import aws_sns_subscriptions as sns_subscriptions
from aws_cdk import aws_sqs as sqs
from aws_cdk import aws_sqs_event_source as sqs_event_source
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3_notifications
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_lambda_python as _lambda_python
from aws_cdk import aws_apigateway as apigw
from aws_cdk import aws_sns as sns
from aws_cdk import aws_sns_subscriptions as sns_subscriptions
from aws_cdk import aws_sqs as sqs
from aws_cdk import aws_sqs_event_source as sqs_event_source
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3_notifications
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_lambda_python as _lambda_python
from aws_cdk import aws_apigateway as apigw
from aws_cdk import aws_sns as sns
from aws_cdk import aws_sns_subscriptions as sns_subscriptions
from aws_cdk import aws_sqs as sqs
from aws_cdk import aws_sqs_event_source as sqs_event_source
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3_notifications
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_lambda_python as _lambda_python
from aws_cdk import aws_apigateway as apigw
from aws_cdk import aws_sns as sns
from aws_cdk import aws_sns_subscriptions as sns_subscriptions
from aws_cdk import aws_sqs as sqs
from aws_cdk import aws_sqs_event_source as sqs_event_source
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3_notifications
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_lambda_python as _lambda_python
from aws_cdk import aws_apigateway as apigw
from aws_cdk import aws_sns as sns
from aws_cdk import aws_sns_subscriptions as sns_subscriptions
from aws_cdk import aws_sqs as sqs
from aws_cdk import aws_sqs_event_source as sqs_event_source
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3_notifications
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_lambda_python as _lambda_python
from aws_cdk import aws_apigateway as apigw
from aws_cdk import aws_sns as sns
from aws_cdk import aws_sns_subscriptions as sns_subscriptions
from aws_cdk import aws_sqs as sqs
from aws_cdk import aws_sqs_event_source as sqs_event_source
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3_notifications
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_lambda_python as _lambda_python
from aws_cdk import aws_apigateway as apigw
from aws