While it's possible to configure CORS to accept requests from all sources, this is generally not recommended as it can introduce security vulnerabilities. Here's a secure way to configure CORS in Django:

```python
from django.conf import settings
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import ensure_csrf_cookie
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_control
from django.views.decorators.vary import vary_on_headers
from django.views.decorators.http import require_safe
from django.views.decorators.csrf import csrf_exempt
from django.core.cache import cache
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.core.cache.backends.locmem import LocMemCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.redis import RedisCache
from django.core.cache.backends.cached_db import CachedDBCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.locmem import LocMemCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends.filebased import FileBasedCache
from django.core.cache.backends.db import DatabaseCache
from django.core.cache.backends.memcached import MemcachedCache
from django.core.cache.backends